### ISSUE TITLE
Stolen implementations

### ISSUE THREAD

**Issue by szaghi** [tomedunn/fortran-string-utility-module#1]
Dear @tomedunn 

This is just to tell you that I am greatly "inspiring" my `string` to your string module, e.g. see [this](http://szaghi.github.io/StringiFor/proc/is_integer.html)

I hope this is ok for you.

Thank you very much for sharing your great work!

Stefano

**Comment by tomedunn** [comment]
Cool! I'm glad to hear you found it useful! :smile:
